import Graph as g

# newgraph = g.Graph('A')
# newgraph.addvertex('B')
# newgraph.addvertex('C')
# newgraph.addvertex('D')
# newgraph.addvertex('E')
# newgraph.addvertex('F')
# newgraph.addvertex('G')
#
# newgraph.addedge('A', 'B', 20)
# newgraph.addedge('A', 'C', 10)
# newgraph.addedge('A', 'E', 30)
# newgraph.addedge('B', 'F', 6)
# newgraph.addedge('B', 'D', 6)
# newgraph.addedge('C', 'F', 5)
# newgraph.addedge('C', 'G', 4)
#
# newgraph.addedge('G', 'E', 12)
# newgraph.addedge('F', 'D', 10)
# newgraph.addedge('E', 'D', 13)
# newgraph.createVisitedNodes()
# newgraph.UCS('A', 'D')

newgraph = g.Graph('A',True)
newgraph.addvertex('B')
newgraph.addvertex('C')
newgraph.addvertex('D')
newgraph.addvertex('E')
newgraph.addvertex('F')
newgraph.addvertex('L')
newgraph.addvertex('O')
newgraph.addvertex('M')
newgraph.addvertex('J')
newgraph.addvertex('H')
newgraph.addvertex('I')
newgraph.addvertex('K1')
newgraph.addvertex('K2')
newgraph.addvertex('K3')
newgraph.addedge('A','B',10)
newgraph.addedge('A','C',14)
newgraph.addedge('B','F',8)
newgraph.addedge('B','H',9)
newgraph.addedge('F','I',4)
newgraph.addedge('F','K1',20)
newgraph.addedge('H','J',12)
newgraph.addedge('H','K2',18)
newgraph.addedge('C','E',11)
newgraph.addedge('C','D',5)
newgraph.addedge('E','L',3)
newgraph.addedge('E','M',10)
newgraph.addedge('D','K3',3)
newgraph.addedge('D','O',7)
newgraph.createVisitedNodes()
newgraph.UCS('A', ('K1','K2','K3'))